#!/bin/sh

if ! service restart "$1" ; then
    # This is an annoyingly effective kludge to get around
    # linuxkit/linuxkit#3586 where sometimes containers can't be
    # restarted, but getting rid of them and recreating them works.
    # Furthermore there are some sleeps to work around various locks
    # and state in the filesystem timing out.
    ctr -n services.linuxkit task rm -f "$1"
    sleep 2
    ctr -n services.linuxkit container rm "$1"
    sleep 2
    service start "$1"
fi
